language: r
cache: packages
sudo: false

services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libpq-dev

before_script:
  - Rscript -e 'toxiproxyr:::toxiproxy_start_ci(".toxiproxy")'
