language: r
cache: packages
sudo: false

services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libpq-dev

before_script:
  - R -e 'toxiproxyr:::copy_scripts(".toxiproxy")' && ./toxiproxy_start.R .toxiproxy
